import images from './images'
import icons from './icons'
import { COLORS, FONT, SIZES, SHADOWS } from './theme'

export { images, icons, COLORS, FONT, SIZES, SHADOWS }

export const data = [
  {
    job_id: '73zCkxqdIadldND8AAACCC==',
    employer_name: 'HYR Global Source Inc',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcfAXIo4plVpb6OYTNXelx97yGK6kEOB6kxUEZ&s=0',
    employer_website: null,
    employer_company_type: null,
    employer_linkedin: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'CONTRACTOR',
    job_title: 'Java React Backend developer@Bentonville AR(W2 only, All VISA)',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/java-react-backend-developer%40bentonville-ar-w2-only-all-visa-at-hyr-global-source-inc-4037586533?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6231,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/java-react-backend-developer%40bentonville-ar-w2-only-all-visa-at-hyr-global-source-inc-4037586533?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
        is_direct: false,
      },
    ],
    job_description:
      'Hi, I hope you are doing well. This is Abhishek from HYR Global Source, we are recruiting for one of our major clients. Please check the below requirement and if you are comfortable, please share your resume at abhishekp@hyrglobalsource.com Role: Java React Backend Developer(Strictly W2 ) Location: Bentonville, AR (3 days onsite/week) Duration: 12 Months + Extension Visa: USC, GC, H1B Transfer, EAD Job Description • Strong Experience building customizable, reusable, accessible cross-platform and dynamic frontend components using Node JS/Express ReactJS, JavaScript, SQL/MySQL/MSSQL, REST services. • Experience building a responsive, cross-browser compatible and high-performance micro frontend web application. • Hands on experience in Cloud platforms (Azure), GCP, git, Jenkins, Kubernetes. • Strong skills in messaging platforms like Kafka. • Strong Experience working with SQL Databases and familiarity with NoSQL databases like cosmos DB and Graph DB. • Hands on development skills to prototype technical solutions. • Knowledge of open-source libraries, design patterns and micro-service architecture. • Experience leveraging AI/ML to build custom models is a plus. • Any experience in device telemetry and hardware integrations is a plus. --------------------------------------- Responsibilities: • Designing, Developing and maintaining software systems that provide telemetry and analytics for enterprise device and conference room technology environments. This includes developing code for data collection and processing, creating and optimizing self-healing workflows. • Work with hardware teams to integrate various technologies and devices that provide telemetry data (e.g. Audio/video equipment) • Collaborate with UI/UX designers to create intuitive and user-friendly interfaces for monitoring and managing conference room telemetry. • Perform rigorous testing and debugging of software to endure reliability and performance. Implement automated testing frameworks where applicable. • Create and maintain comprehensive documentation for software development designs, APIs and user guides. • Continuously monitor and optimize the performance of telemetry systems to handle large volumes of data efficiently. • Ensure the software systems are secure and comply with data privacy regulations and best practices. ------------------------------------------------ Thanks & Regards Abhishek Panwar | Sr. Lead Recruiter Follow us over Linkedin - https://www.linkedin.com/company/hyr-global-source-inc To Get more job notifications Abhishekp@hyrglobalsource.com',
    job_is_remote: false,
    job_posted_at_timestamp: 1727819991,
    job_posted_at_datetime_utc: '2024-10-01T21:59:51.000Z',
    job_city: 'Bentonville',
    job_state: 'AR',
    job_country: 'US',
    job_latitude: 36.372356,
    job_longitude: -94.21021,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&udm=8#vhid=vt%3D20/docid%3D73zCkxqdIcoldND8AAAAAA%3D%3D&vssid=jobs-detail-viewer',
    job_offer_expiration_datetime_utc: '2024-10-31T21:59:50.000Z',
    job_offer_expiration_timestamp: 1730411990,
    job_required_experience: {
      no_experience_required: 'false',
      required_experience_in_months: null,
      experience_mentioned: 'true',
      experience_preferred: 'true',
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: 'false',
      professional_certification: 'false',
      high_school: 'false',
      associates_degree: 'false',
      bachelors_degree: 'true',
      degree_mentioned: 'false',
      degree_preferred: 'false',
      professional_certification_mentioned: 'false',
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Experience building a responsive, cross-browser compatible and high-performance micro frontend web application',
        'Hands on experience in Cloud platforms (Azure), GCP, git, Jenkins, Kubernetes',
        'Strong skills in messaging platforms like Kafka',
        'Strong Experience working with SQL Databases and familiarity with NoSQL databases like cosmos DB and Graph DB',
        'Hands on development skills to prototype technical solutions',
        'Knowledge of open-source libraries, design patterns and micro-service architecture',
      ],
      Responsibilities: [
        'Designing, Developing and maintaining software systems that provide telemetry and analytics for enterprise device and conference room technology environments',
        'This includes developing code for data collection and processing, creating and optimizing self-healing workflows',
        'Work with hardware teams to integrate various technologies and devices that provide telemetry data (e.g. Audio/video equipment)',
        'Collaborate with UI/UX designers to create intuitive and user-friendly interfaces for monitoring and managing conference room telemetry',
        'Perform rigorous testing and debugging of software to endure reliability and performance',
        'Implement automated testing frameworks where applicable',
        'Create and maintain comprehensive documentation for software development designs, APIs and user guides',
        'Continuously monitor and optimize the performance of telemetry systems to handle large volumes of data efficiently',
        'Ensure the software systems are secure and comply with data privacy regulations and best practices',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: '13zCkxqdIcoldND8AAEEAA==',
    employer_name: 'HYR Global Source Inc',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcfAXIo4plVpb6OYTNXelx97yGK6kEOB6kxUEZ&s=0',
    employer_website: null,
    employer_company_type: null,
    employer_linkedin: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'CONTRACTOR',
    job_title: 'Java React Backend developer@Bentonville AR(W2 only, All VISA)',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/java-react-backend-developer%40bentonville-ar-w2-only-all-visa-at-hyr-global-source-inc-4037586533?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6231,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/java-react-backend-developer%40bentonville-ar-w2-only-all-visa-at-hyr-global-source-inc-4037586533?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
        is_direct: false,
      },
    ],
    job_description:
      'Hi, I hope you are doing well. This is Abhishek from HYR Global Source, we are recruiting for one of our major clients. Please check the below requirement and if you are comfortable, please share your resume at abhishekp@hyrglobalsource.com Role: Java React Backend Developer(Strictly W2 ) Location: Bentonville, AR (3 days onsite/week) Duration: 12 Months + Extension Visa: USC, GC, H1B Transfer, EAD Job Description • Strong Experience building customizable, reusable, accessible cross-platform and dynamic frontend components using Node JS/Express ReactJS, JavaScript, SQL/MySQL/MSSQL, REST services. • Experience building a responsive, cross-browser compatible and high-performance micro frontend web application. • Hands on experience in Cloud platforms (Azure), GCP, git, Jenkins, Kubernetes. • Strong skills in messaging platforms like Kafka. • Strong Experience working with SQL Databases and familiarity with NoSQL databases like cosmos DB and Graph DB. • Hands on development skills to prototype technical solutions. • Knowledge of open-source libraries, design patterns and micro-service architecture. • Experience leveraging AI/ML to build custom models is a plus. • Any experience in device telemetry and hardware integrations is a plus. --------------------------------------- Responsibilities: • Designing, Developing and maintaining software systems that provide telemetry and analytics for enterprise device and conference room technology environments. This includes developing code for data collection and processing, creating and optimizing self-healing workflows. • Work with hardware teams to integrate various technologies and devices that provide telemetry data (e.g. Audio/video equipment) • Collaborate with UI/UX designers to create intuitive and user-friendly interfaces for monitoring and managing conference room telemetry. • Perform rigorous testing and debugging of software to endure reliability and performance. Implement automated testing frameworks where applicable. • Create and maintain comprehensive documentation for software development designs, APIs and user guides. • Continuously monitor and optimize the performance of telemetry systems to handle large volumes of data efficiently. • Ensure the software systems are secure and comply with data privacy regulations and best practices. ------------------------------------------------ Thanks & Regards Abhishek Panwar | Sr. Lead Recruiter Follow us over Linkedin - https://www.linkedin.com/company/hyr-global-source-inc To Get more job notifications Abhishekp@hyrglobalsource.com',
    job_is_remote: false,
    job_posted_at_timestamp: 1727819991,
    job_posted_at_datetime_utc: '2024-10-01T21:59:51.000Z',
    job_city: 'Bentonville',
    job_state: 'AR',
    job_country: 'US',
    job_latitude: 36.372356,
    job_longitude: -94.21021,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&udm=8#vhid=vt%3D20/docid%3D73zCkxqdIcoldND8AAAAAA%3D%3D&vssid=jobs-detail-viewer',
    job_offer_expiration_datetime_utc: '2024-10-31T21:59:50.000Z',
    job_offer_expiration_timestamp: 1730411990,
    job_required_experience: {
      no_experience_required: 'false',
      required_experience_in_months: null,
      experience_mentioned: 'true',
      experience_preferred: 'true',
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: 'false',
      professional_certification: 'false',
      high_school: 'false',
      associates_degree: 'false',
      bachelors_degree: 'true',
      degree_mentioned: 'false',
      degree_preferred: 'false',
      professional_certification_mentioned: 'false',
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Experience building a responsive, cross-browser compatible and high-performance micro frontend web application',
        'Hands on experience in Cloud platforms (Azure), GCP, git, Jenkins, Kubernetes',
        'Strong skills in messaging platforms like Kafka',
        'Strong Experience working with SQL Databases and familiarity with NoSQL databases like cosmos DB and Graph DB',
        'Hands on development skills to prototype technical solutions',
        'Knowledge of open-source libraries, design patterns and micro-service architecture',
      ],
      Responsibilities: [
        'Designing, Developing and maintaining software systems that provide telemetry and analytics for enterprise device and conference room technology environments',
        'This includes developing code for data collection and processing, creating and optimizing self-healing workflows',
        'Work with hardware teams to integrate various technologies and devices that provide telemetry data (e.g. Audio/video equipment)',
        'Collaborate with UI/UX designers to create intuitive and user-friendly interfaces for monitoring and managing conference room telemetry',
        'Perform rigorous testing and debugging of software to endure reliability and performance',
        'Implement automated testing frameworks where applicable',
        'Create and maintain comprehensive documentation for software development designs, APIs and user guides',
        'Continuously monitor and optimize the performance of telemetry systems to handle large volumes of data efficiently',
        'Ensure the software systems are secure and comply with data privacy regulations and best practices',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: '00zCkxqdIcoldND8DDDDDD==',
    employer_name: 'HYR Global Source Inc',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcfAXIo4plVpb6OYTNXelx97yGK6kEOB6kxUEZ&s=0',
    employer_website: null,
    employer_company_type: null,
    employer_linkedin: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'CONTRACTOR',
    job_title: 'Java React Backend developer@Bentonville AR(W2 only, All VISA)',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/java-react-backend-developer%40bentonville-ar-w2-only-all-visa-at-hyr-global-source-inc-4037586533?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6231,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/java-react-backend-developer%40bentonville-ar-w2-only-all-visa-at-hyr-global-source-inc-4037586533?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
        is_direct: false,
      },
    ],
    job_description:
      'Hi, I hope you are doing well. This is Abhishek from HYR Global Source, we are recruiting for one of our major clients. Please check the below requirement and if you are comfortable, please share your resume at abhishekp@hyrglobalsource.com Role: Java React Backend Developer(Strictly W2 ) Location: Bentonville, AR (3 days onsite/week) Duration: 12 Months + Extension Visa: USC, GC, H1B Transfer, EAD Job Description • Strong Experience building customizable, reusable, accessible cross-platform and dynamic frontend components using Node JS/Express ReactJS, JavaScript, SQL/MySQL/MSSQL, REST services. • Experience building a responsive, cross-browser compatible and high-performance micro frontend web application. • Hands on experience in Cloud platforms (Azure), GCP, git, Jenkins, Kubernetes. • Strong skills in messaging platforms like Kafka. • Strong Experience working with SQL Databases and familiarity with NoSQL databases like cosmos DB and Graph DB. • Hands on development skills to prototype technical solutions. • Knowledge of open-source libraries, design patterns and micro-service architecture. • Experience leveraging AI/ML to build custom models is a plus. • Any experience in device telemetry and hardware integrations is a plus. --------------------------------------- Responsibilities: • Designing, Developing and maintaining software systems that provide telemetry and analytics for enterprise device and conference room technology environments. This includes developing code for data collection and processing, creating and optimizing self-healing workflows. • Work with hardware teams to integrate various technologies and devices that provide telemetry data (e.g. Audio/video equipment) • Collaborate with UI/UX designers to create intuitive and user-friendly interfaces for monitoring and managing conference room telemetry. • Perform rigorous testing and debugging of software to endure reliability and performance. Implement automated testing frameworks where applicable. • Create and maintain comprehensive documentation for software development designs, APIs and user guides. • Continuously monitor and optimize the performance of telemetry systems to handle large volumes of data efficiently. • Ensure the software systems are secure and comply with data privacy regulations and best practices. ------------------------------------------------ Thanks & Regards Abhishek Panwar | Sr. Lead Recruiter Follow us over Linkedin - https://www.linkedin.com/company/hyr-global-source-inc To Get more job notifications Abhishekp@hyrglobalsource.com',
    job_is_remote: false,
    job_posted_at_timestamp: 1727819991,
    job_posted_at_datetime_utc: '2024-10-01T21:59:51.000Z',
    job_city: 'Bentonville',
    job_state: 'AR',
    job_country: 'US',
    job_latitude: 36.372356,
    job_longitude: -94.21021,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&udm=8#vhid=vt%3D20/docid%3D73zCkxqdIcoldND8AAAAAA%3D%3D&vssid=jobs-detail-viewer',
    job_offer_expiration_datetime_utc: '2024-10-31T21:59:50.000Z',
    job_offer_expiration_timestamp: 1730411990,
    job_required_experience: {
      no_experience_required: 'false',
      required_experience_in_months: null,
      experience_mentioned: 'true',
      experience_preferred: 'true',
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: 'false',
      professional_certification: 'false',
      high_school: 'false',
      associates_degree: 'false',
      bachelors_degree: 'true',
      degree_mentioned: 'false',
      degree_preferred: 'false',
      professional_certification_mentioned: 'false',
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Experience building a responsive, cross-browser compatible and high-performance micro frontend web application',
        'Hands on experience in Cloud platforms (Azure), GCP, git, Jenkins, Kubernetes',
        'Strong skills in messaging platforms like Kafka',
        'Strong Experience working with SQL Databases and familiarity with NoSQL databases like cosmos DB and Graph DB',
        'Hands on development skills to prototype technical solutions',
        'Knowledge of open-source libraries, design patterns and micro-service architecture',
      ],
      Responsibilities: [
        'Designing, Developing and maintaining software systems that provide telemetry and analytics for enterprise device and conference room technology environments',
        'This includes developing code for data collection and processing, creating and optimizing self-healing workflows',
        'Work with hardware teams to integrate various technologies and devices that provide telemetry data (e.g. Audio/video equipment)',
        'Collaborate with UI/UX designers to create intuitive and user-friendly interfaces for monitoring and managing conference room telemetry',
        'Perform rigorous testing and debugging of software to endure reliability and performance',
        'Implement automated testing frameworks where applicable',
        'Create and maintain comprehensive documentation for software development designs, APIs and user guides',
        'Continuously monitor and optimize the performance of telemetry systems to handle large volumes of data efficiently',
        'Ensure the software systems are secure and comply with data privacy regulations and best practices',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
]

export const Data = {
  job_id: '33zCkxqdIco4tldND8BBAAAA==',
  employer_name: 'HYR Global Source Inc',
  employer_logo:
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcfAXIo4plVpb6OYTNXelx97yGK6kEOB6kxUEZ&s=0',
  employer_website: null,
  employer_company_type: null,
  employer_linkedin: null,
  job_publisher: 'LinkedIn',
  job_employment_type: 'CONTRACTOR',
  job_title: 'Java React Backend developer@Bentonville AR(W2 only, All VISA)',
  job_apply_link:
    'https://www.linkedin.com/jobs/view/java-react-backend-developer%40bentonville-ar-w2-only-all-visa-at-hyr-global-source-inc-4037586533?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
  job_apply_is_direct: false,
  job_apply_quality_score: 0.6231,
  apply_options: [
    {
      publisher: 'LinkedIn',
      apply_link:
        'https://www.linkedin.com/jobs/view/java-react-backend-developer%40bentonville-ar-w2-only-all-visa-at-hyr-global-source-inc-4037586533?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic',
      is_direct: false,
    },
  ],
  job_description:
    'Hi, I hope you are doing well. This is Abhishek from HYR Global Source, we are recruiting for one of our major clients. Please check the below requirement and if you are comfortable, please share your resume at abhishekp@hyrglobalsource.com Role: Java React Backend Developer(Strictly W2 ) Location: Bentonville, AR (3 days onsite/week) Duration: 12 Months + Extension Visa: USC, GC, H1B Transfer, EAD Job Description • Strong Experience building customizable, reusable, accessible cross-platform and dynamic frontend components using Node JS/Express ReactJS, JavaScript, SQL/MySQL/MSSQL, REST services. • Experience building a responsive, cross-browser compatible and high-performance micro frontend web application. • Hands on experience in Cloud platforms (Azure), GCP, git, Jenkins, Kubernetes. • Strong skills in messaging platforms like Kafka. • Strong Experience working with SQL Databases and familiarity with NoSQL databases like cosmos DB and Graph DB. • Hands on development skills to prototype technical solutions. • Knowledge of open-source libraries, design patterns and micro-service architecture. • Experience leveraging AI/ML to build custom models is a plus. • Any experience in device telemetry and hardware integrations is a plus. --------------------------------------- Responsibilities: • Designing, Developing and maintaining software systems that provide telemetry and analytics for enterprise device and conference room technology environments. This includes developing code for data collection and processing, creating and optimizing self-healing workflows. • Work with hardware teams to integrate various technologies and devices that provide telemetry data (e.g. Audio/video equipment) • Collaborate with UI/UX designers to create intuitive and user-friendly interfaces for monitoring and managing conference room telemetry. • Perform rigorous testing and debugging of software to endure reliability and performance. Implement automated testing frameworks where applicable. • Create and maintain comprehensive documentation for software development designs, APIs and user guides. • Continuously monitor and optimize the performance of telemetry systems to handle large volumes of data efficiently. • Ensure the software systems are secure and comply with data privacy regulations and best practices. ------------------------------------------------ Thanks & Regards Abhishek Panwar | Sr. Lead Recruiter Follow us over Linkedin - https://www.linkedin.com/company/hyr-global-source-inc To Get more job notifications Abhishekp@hyrglobalsource.com',
  job_is_remote: false,
  job_posted_at_timestamp: 1727819991,
  job_posted_at_datetime_utc: '2024-10-01T21:59:51.000Z',
  job_city: 'Bentonville',
  job_state: 'AR',
  job_country: 'US',
  job_latitude: 36.372356,
  job_longitude: -94.21021,
  job_benefits: null,
  job_google_link:
    'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&udm=8#vhid=vt%3D20/docid%3D73zCkxqdIcoldND8AAAAAA%3D%3D&vssid=jobs-detail-viewer',
  job_offer_expiration_datetime_utc: '2024-10-31T21:59:50.000Z',
  job_offer_expiration_timestamp: 1730411990,
  job_required_experience: {
    no_experience_required: 'false',
    required_experience_in_months: null,
    experience_mentioned: 'true',
    experience_preferred: 'true',
  },
  job_required_skills: null,
  job_required_education: {
    postgraduate_degree: 'false',
    professional_certification: 'false',
    high_school: 'false',
    associates_degree: 'false',
    bachelors_degree: 'true',
    degree_mentioned: 'false',
    degree_preferred: 'false',
    professional_certification_mentioned: 'false',
  },
  job_experience_in_place_of_education: false,
  job_min_salary: null,
  job_max_salary: null,
  job_salary_currency: null,
  job_salary_period: null,
  job_highlights: {
    Qualifications: [
      'Experience building a responsive, cross-browser compatible and high-performance micro frontend web application',
      'Hands on experience in Cloud platforms (Azure), GCP, git, Jenkins, Kubernetes',
      'Strong skills in messaging platforms like Kafka',
      'Strong Experience working with SQL Databases and familiarity with NoSQL databases like cosmos DB and Graph DB',
      'Hands on development skills to prototype technical solutions',
      'Knowledge of open-source libraries, design patterns and micro-service architecture',
    ],
    Responsibilities: [
      'Designing, Developing and maintaining software systems that provide telemetry and analytics for enterprise device and conference room technology environments',
      'This includes developing code for data collection and processing, creating and optimizing self-healing workflows',
      'Work with hardware teams to integrate various technologies and devices that provide telemetry data (e.g. Audio/video equipment)',
      'Collaborate with UI/UX designers to create intuitive and user-friendly interfaces for monitoring and managing conference room telemetry',
      'Perform rigorous testing and debugging of software to endure reliability and performance',
      'Implement automated testing frameworks where applicable',
      'Create and maintain comprehensive documentation for software development designs, APIs and user guides',
      'Continuously monitor and optimize the performance of telemetry systems to handle large volumes of data efficiently',
      'Ensure the software systems are secure and comply with data privacy regulations and best practices',
    ],
  },
  job_job_title: null,
  job_posting_language: 'en',
  job_onet_soc: '15113400',
  job_onet_job_zone: '3',
  job_occupational_categories: null,
  job_naics_code: null,
  job_naics_name: null,
}
